langs/fr_FR/dolismq.lang, view/control/control_card.php, view/sheet/sheet_card.php
=> #417 [Sheet] add: remove backtopage and control button on sheet card

css/scss/element/index.php, css/scss/modules/index.php, css/scss/variable/index.php, js/modules/index.php
=> #804 [Core] add: index file in css & js directories

view/control/control_card.php
=> #883 #886 [IHM] fix: ihm button on control card

core/modules/dolismq/answer/mod_answer_standard.php, core/modules/dolismq/control/mod_control_standard.php, core/modules/dolismq/controldet/mod_controldet_standard.php, core/modules/dolismq/dolismqdocuments/controldocument/mod_controldocument_standard.php, core/modules/dolismq/question/mod_question_standard.php, core/modules/dolismq/sheet/mod_sheet_standard.php, lib/dolismq.lib.php
=> #861 [Mod] add: rework mod num ref with ModeleNumRefSaturne

core/modules/modDoliSMQ.class.php, sql/control/llx_c_control_attendants_role.sql, sql/data.sql
=> #885 [SQL] add: control_attendants_role dictionary

core/boxes/dolismqwidget1.php
=> #898 [Control] fix: missing getNomUrl on box

class/control.class.php, core/modules/dolismq/dolismqdocuments/controldocument/doc_controldocument_odt.modules.php, core/modules/modDoliSMQ.class.php, core/tpl/dolismq_control_list.tpl.php, core/triggers/interface_99_modDoliSMQ_DoliSMQTriggers.class.php, view/control/control_card.php, view/control/control_list.php
=> #903 [Control] fix: fatal with $object->linkedObjects cause "dolibarr name"

core/modules/modDoliSMQ.class.php
=> #904 [Mod] fix: need value instead of global value

view/control/control_card.php
=> #859 [Control] fix: need reset answer counter for action setValidated

view/control/control_card.php
=> #768 [Control] add: use select array instead of dolismq_select_product_lots

view/control/control_card.php
=> #860 [Control] fix: remove picto help confirm validated

admin/documents.php, core/modules/dolismq/dolismqdocuments/controldocument/doc_controldocument_odt.modules.php, core/modules/modDoliSMQ.class.php, documents/temp/index.php, view/control/control_card.php
=> #917 [Control] add: generation ODT public interface

core/modules/dolismq/dolismqdocuments/controldocument/doc_controldocument_odt.modules.php, view/control/control_card.php
=> #951 [ODT] add: rework doc with generic functions ModeleDocSaturne

class/control.class.php
close #947
remettre filtres status > 0 pour enlever les supprimés
=> #947 [Control] fix: dashboard performance issue due to load fetchObjectLinked

core/modules/dolismq/dolismqdocuments/controldocument/doc_controldocument_odt.modules.php
=> #967 [ODT] fix: missing trad ODT

core/modules/dolismq/dolismqdocuments/controldocument/doc_controldocument_odt.modules.php
=> #978 [ODT] fix: camelCase

lib/dolismq_control.lib.php, view/control/control_card.php
=> #988 [Class] add: use ControlDocument class for ODT generation

view/question/question_card.php
=> Revert "#984 [Question] add: cancel button when editing answer"

view/control/control_card.php
=> #1000 [Control] add: send email function with doc

view/question/question_card.php
=> #1015 [Question] add: don't add answer for type 'OkKo' &&  'OkKoToFixNonApplicable'

class/control.class.php
=> #1018 [Control] fix: set default value for arrayNbControlByVerdict dashboard

core/tpl/dolismq_control_list.tpl.php, view/control/control_list.php
=> #1040 [Control] add: control list name

view/sheet/sheet_card.php
=> #1030 [Sheet] add: change trad for use same

sql/answer/llx_dolismq_answer.key.sql
=> #1037 [SQL] add: missing Answer SQL key

sql/update.sql
=> #1063 [SQL] fix: backward compatibility question type

view/question/question_card.php
=> #1054 [Question] add: remove action on question type OkKo/OkKoToFixNonApplicable

core/modules/modDoliSMQ.class.php
=> #773 [Mod] add: qc_frequency extrafields

class/answer.class.php, core/modules/modDoliSMQ.class.php
=> #1091 [Mod] fix: missing answer on question with preset type OkKoToFixNonApplicable

langs/fr_FR/dolismq.lang
=> #1149 [ODT] fix: bug generation pdf due to ASCII characters

admin/sheet.php
=> #1178 [AdminConf] fix: fatal sheet const array

langs/fr_FR/dolismq.lang
=> #1151 [Trad] fix: change trad

view/control/control_list.php
=> #1195 [Control] fix: error check categories on box

core/modules/dolismq/dolismqdocuments/controldocument/doc_controldocument_odt.modules.php
=> #1197 [ODT] fix: missing ODT trad companies

view/control/control_card.php, view/question/question_card.php, view/sheet/sheet_card.php
=> #1124 [Mod] fix: fatal events button card

class/control.class.php, core/modules/modDoliSMQ.class.php, view/control/control_card.php
=> #1130 [PublicControl] fix: missing '.php' in path url

view/control/control_card.php, view/question/question_card.php, view/sheet/sheet_card.php
=> #1059 [Mod] add: create button tags

view/question/question_card.php
=> #1095 [Question] fix: getpost question type on error

view/control/control_list.php
=> #1133 [Control] add: status field in control_list

view/control/control_card.php
=> #1240 [Control] add: remove unused confirm_delete action
